### ISSUE TITLE
Provide bootstrap for sample cache configuration

### ISSUE THREAD

**Issue by rkovarik** [vpro/jsr107-magnolia#2]
When using non persistent ehcache on nonserializable objects, the persistence has to be turned off:
/modules/cache/config/cacheFactory/caches/CACHE_NAME/persistence@strategy=none
It would be cool if this could be preconfigured and provided as a sample bootstrap file (instead of the cache configuration screenshot)

`2016-05-09 14:00:44,119 ERROR net.sf.ehcache.store.disk.DiskStorageFactory      : Disk Write of org.jsr107.ri.annotations.DefaultGeneratedCacheKey@56833e4a failed: 
java.io.NotSerializableException: info.magnolia.module.site.ConfiguredSite
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at net.sf.ehcache.Element.writeObject(Element.java:875)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at net.sf.ehcache.util.MemoryEfficientByteArrayOutputStream.serialize(MemoryEfficientByteArrayOutputStream.java:97)
	at net.sf.ehcache.store.disk.DiskStorageFactory.serializeElement(DiskStorageFactory.java:403)
	at net.sf.ehcache.store.disk.DiskStorageFactory.write(DiskStorageFactory.java:385)
	at net.sf.ehcache.store.disk.DiskStorageFactory$DiskWriteTask.call(DiskStorageFactory.java:477)
	at net.sf.ehcache.store.disk.DiskStorageFactory$PersistentDiskWriteTask.call(DiskStorageFactory.java:1071)
	at net.sf.ehcache.store.disk.DiskStorageFactory$PersistentDiskWriteTask.call(DiskStorageFactory.java:1055)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by mihxil** [comment]
I was wondering whether yaml configuration for this was upcoming?

**Comment by rkovarik** [comment]
Not on the horizon since the admin stuff is still not exposed to the resource origin and not so many people dare to deal with cache config as you do :-)

**Comment by mihxil** [comment]
I think it is a bit odd to bootstrap example configuration in a generic tool.

I added a utility nl.vpro.magnolia.jsr107.CreateConfigurationTasks#nl.vpro.magnolia.jsr107.CreateConfigurationTasks#createConfigurationTasks which can be added to a version handler to create default configuration for the caches. This can then be manually finetuned.

**Comment by mihxil** [comment]
Actually I generalized code a bit. I think it can now be used to configure all caches by code. See README.
